name: CI

# Trigger the workflow on push or pull request, but only for the main branch
on:
  pull_request:
  push:
    branches: [main]

jobs:
  cabal:
    name: Cabal / ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        cabal: ["latest"]
        ghc: ["9.0", "8.10", "8.8", "8.6"]

    steps:
    - name: Check out code
      uses: actions/checkout@v2.3.3
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/main'

    - name: Setup Haskell
      uses: haskell/actions/setup@v1
      id: setup-haskell-cabal
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - name: Calculate build plan
      run: cabal v2-freeze

    - name: Enable caching
      uses: actions/cache@v2.1.2
      with:
        path: |
          ~/.cabal/store
          ~/.cabal/packages
        key: cabal-${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}

    - name: Build
      run: |
        cabal v2-configure --enable-tests --enable-benchmarks --test-show-details=direct
        cabal v2-build all

    - name: Test
      run: cabal v2-test --test-show-details=direct all

  stack:
    name: Stack / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        stack: ["latest"]

    steps:
    - name: Check out code
      uses: actions/checkout@v2.3.3
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/main'

    - name: Setup Haskell Stack
      uses: actions/setup-haskell@v1.1.3
      with:
        ghc-version: ${{ matrix.ghc }}
        enable-stack: true
        stack-version: ${{ matrix.stack }}
        stack-no-global: true
        stack-setup-ghc: true

    - name: Enable caching
      uses: actions/cache@v2.1.2
      with:
        path: ~/.stack
        key: stack-${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('stack.yaml.lock') }}

    - name: Build
      run: |
        stack build --test --bench --no-run-tests --no-run-benchmarks --ghc-options=-Werror

    - name: Test
      run: |
        stack test

  nix:
    name: Nix
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2.3.3

    - name: Install Nix
      uses: cachix/install-nix-action@v12
      with:
        extra_nix_config: |
          substituters = http://cache.nixos.org https://hydra.iohk.io
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=

    - name: Build
      run: nix-build -A injection.components.library

    - name: Test
      run: nix-build -A injection.checks
